# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c73b62d3e145f9669ac5009ec9b5d0df74f198193369a51b7a80ce28968782d1319453a19ac79bcad36f21fd16626d2dcdaa8f4074e1782447155175728db87

test:
  secret_key_base: 101df0b397ab2dd60537ed1fef5ef18af06e5880a34d3ab8b12d7f7353755d985fbc5fd137a1875648c92e87de3c854a52459d31b214f8701062f38ea8accf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
